import 'package:equatable/equatable.dart';

import '../../l10n/app_localizations.dart';

enum PackingCategory {
  clothing, electronics, documents, hygiene,
  medicine, food, accessories, sports, other,
}

extension PackingCategoryLabel on PackingCategory {
  String get label => switch (this) {
    PackingCategory.clothing     => 'Ropa',
    PackingCategory.electronics  => 'Electrónica',
    PackingCategory.documents    => 'Documentos',
    PackingCategory.hygiene      => 'Higiene',
    PackingCategory.medicine     => 'Medicamentos',
    PackingCategory.food         => 'Alimentación',
    PackingCategory.accessories  => 'Accesorios',
    PackingCategory.sports       => 'Deporte',
    PackingCategory.other        => 'Otros',
  };

  String localizedLabel(AppLocalizations l10n) => switch (this) {
    PackingCategory.clothing     => l10n.catClothing,
    PackingCategory.electronics  => l10n.catElectronics,
    PackingCategory.documents    => l10n.catDocuments,
    PackingCategory.hygiene        => l10n.catHygiene,
    PackingCategory.medicine     => l10n.catMedicine,
    PackingCategory.food         => l10n.catFood,
    PackingCategory.accessories  => l10n.catAccessories,
    PackingCategory.sports       => l10n.catSports,
    PackingCategory.other        => l10n.catOther,
  };

  String get emoji => switch (this) {
    PackingCategory.clothing     => '👕',
    PackingCategory.electronics  => '📱',
    PackingCategory.documents    => '📄',
    PackingCategory.hygiene      => '🧴',
    PackingCategory.medicine     => '💊',
    PackingCategory.food         => '🍎',
    PackingCategory.accessories  => '👜',
    PackingCategory.sports       => '⚽',
    PackingCategory.other        => '📦',
  };
}

class PackingItem extends Equatable {
  final String id;
  final String listId;
  final String tripId;
  final String userId;  // Added for SQLite
  final String name;
  final PackingCategory category;
  final bool isPacked;
  final bool isAutoGenerated;
  final int quantity;
  final int order;
  final String? notes;

  const PackingItem({
    required this.id,
    required this.listId,
    required this.tripId,
    this.userId = '',  // Added for SQLite
    required this.name,
    this.category = PackingCategory.other,
    this.isPacked = false,
    this.isAutoGenerated = false,
    this.quantity = 1,
    this.order = 0,
    this.notes,
  });

  PackingItem copyWith({
    String? id, String? listId, String? tripId, String? userId,
    String? name, PackingCategory? category, bool? isPacked,
    bool? isAutoGenerated, int? quantity, int? order, String? notes,
  }) => PackingItem(
    id: id ?? this.id, listId: listId ?? this.listId,
    tripId: tripId ?? this.tripId, userId: userId ?? this.userId,
    name: name ?? this.name, category: category ?? this.category,
    isPacked: isPacked ?? this.isPacked,
    isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    quantity: quantity ?? this.quantity, order: order ?? this.order,
    notes: notes ?? this.notes,
  );

  PackingItem toggle() => copyWith(isPacked: !isPacked);

  @override
  List<Object?> get props => [id, listId, tripId, isPacked, quantity, name];
}

class PackingList extends Equatable {
  final String id;
  final String tripId;
  final String userId;  // Added for SQLite
  final String name;
  final List<PackingItem> items;
  final DateTime createdAt;
  final DateTime updatedAt;  // Added for SQLite

  PackingList({
    required this.id,
    required this.tripId,
    this.userId = '',
    required this.name,
    this.items = const [],
    required this.createdAt,
    DateTime? updatedAt,
  }) : updatedAt = updatedAt ?? createdAt;

  int get totalItems  => items.length;
  int get packedItems => items.where((i) => i.isPacked).length;
  int get progress    => totalItems == 0 ? 0 : ((packedItems / totalItems) * 100).round();

  PackingList copyWith({
    String? id, String? tripId, String? userId,
    String? name, List<PackingItem>? items,
    DateTime? createdAt, DateTime? updatedAt,
  }) => PackingList(
    id: id ?? this.id, tripId: tripId ?? this.tripId,
    userId: userId ?? this.userId,
    name: name ?? this.name, items: items ?? this.items,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
  );

  @override
  List<Object?> get props => [id, tripId, name, items];
}
