// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2mzaQsP4oVsmG1R26JQZES4ire8L_1oI',
    appId: '1:527231712148:web:5f92f82d9b3021f3d4ed81',
    messagingSenderId: '527231712148',
    projectId: 'travelready-app',
    authDomain: 'travelready-app.firebaseapp.com',
    storageBucket: 'travelready-app.firebasestorage.app',
    measurementId: 'G-E24H5X1GDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimHYhClG15J2SHEzqaKE18_wGFNIbTos',
    appId: '1:527231712148:android:4c8640a93b25faaed4ed81',
    messagingSenderId: '527231712148',
    projectId: 'travelready-app',
    storageBucket: 'travelready-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhuwJPvewD7ejBq2lgdAvP511F0kpqUX0',
    appId: '1:527231712148:ios:cb7afa4cb3dd7b71d4ed81',
    messagingSenderId: '527231712148',
    projectId: 'travelready-app',
    storageBucket: 'travelready-app.firebasestorage.app',
    iosBundleId: 'com.buendidev.travelReady',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhuwJPvewD7ejBq2lgdAvP511F0kpqUX0',
    appId: '1:527231712148:ios:cb7afa4cb3dd7b71d4ed81',
    messagingSenderId: '527231712148',
    projectId: 'travelready-app',
    storageBucket: 'travelready-app.firebasestorage.app',
    iosBundleId: 'com.buendidev.travelReady',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2mzaQsP4oVsmG1R26JQZES4ire8L_1oI',
    appId: '1:527231712148:web:974ab7b1fd3bf630d4ed81',
    messagingSenderId: '527231712148',
    projectId: 'travelready-app',
    authDomain: 'travelready-app.firebaseapp.com',
    storageBucket: 'travelready-app.firebasestorage.app',
    measurementId: 'G-5110YCXF8F',
  );
}
