import '../../domain/entities/packing_item.dart';

class PackingItemModel extends PackingItem {
  const PackingItemModel({
    required super.id, required super.listId, required super.tripId,
    super.userId, required super.name, super.category, super.isPacked,
    super.isAutoGenerated, super.quantity, super.order, super.notes,
  });

  // ── SQLite (fromMap/toMap) ────────────────────────────────────────────
  factory PackingItemModel.fromMap(Map<String, dynamic> map) {
    return PackingItemModel(
      id:              map['id']                as String,
      listId:          map['list_id']           as String? ?? '',
      tripId:          map['trip_id']           as String? ?? '',
      userId:          map['user_id']           as String? ?? '',
      name:            map['name']              as String? ?? '',
      category:        _cat(map['category']     as String?),
      isPacked:        (map['is_packed']        as int? ?? 0) == 1,
      isAutoGenerated: (map['is_auto_generated'] as int? ?? 0) == 1,
      quantity:        map['quantity']          as int?    ?? 1,
      order:           map['order_index']       as int?    ?? 0,
      notes:           map['notes']             as String?,
    );
  }

  Map<String, dynamic> toMap() => {
    'id':                id,
    'list_id':           listId,
    'trip_id':           tripId,
    'user_id':           userId,
    'name':              name,
    'category':          category.name,
    'is_packed':         isPacked ? 1 : 0,
    'is_auto_generated': isAutoGenerated ? 1 : 0,
    'quantity':          quantity,
    'order_index':       order,
    if (notes != null) 'notes': notes,
  };

  static PackingItemModel fromEntity(PackingItem i) => PackingItemModel(
    id: i.id, listId: i.listId, tripId: i.tripId, userId: i.userId,
    name: i.name, category: i.category, isPacked: i.isPacked,
    isAutoGenerated: i.isAutoGenerated, quantity: i.quantity,
    order: i.order, notes: i.notes,
  );

  /// Override para que copyWith devuelva PackingItemModel, no PackingItem.
  @override
  PackingItemModel copyWith({
    String? id, String? listId, String? tripId, String? userId,
    String? name, PackingCategory? category, bool? isPacked,
    bool? isAutoGenerated, int? quantity, int? order, String? notes,
  }) => PackingItemModel(
    id:              id              ?? this.id,
    listId:          listId          ?? this.listId,
    tripId:          tripId          ?? this.tripId,
    userId:          userId          ?? this.userId,
    name:            name            ?? this.name,
    category:        category        ?? this.category,
    isPacked:        isPacked        ?? this.isPacked,
    isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    quantity:        quantity        ?? this.quantity,
    order:           order           ?? this.order,
    notes:           notes           ?? this.notes,
  );

  static PackingCategory _cat(String? v) => PackingCategory.values
      .firstWhere((c) => c.name == v, orElse: () => PackingCategory.other);
}

// ── PackingListModel ──────────────────────────────────────────────────────────

class PackingListModel extends PackingList {
  PackingListModel({
    required super.id, required super.tripId, super.userId,
    required super.name, super.items, required super.createdAt,
    super.updatedAt,
  });

  // ── SQLite ───────────────────────────────────────────────────────────────
  factory PackingListModel.fromMap(
    Map<String, dynamic> map, {List<PackingItem> items = const []}) {
    return PackingListModel(
      id:        map['id']         as String,
      tripId:    map['trip_id']    as String? ?? '',
      userId:    map['user_id']    as String? ?? '',
      name:      map['name']       as String? ?? '',
      items:     items,
      createdAt: map['created_at'] != null
          ? DateTime.parse(map['created_at'] as String)
          : DateTime.now(),
      updatedAt: map['updated_at'] != null
          ? DateTime.parse(map['updated_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toMap() => {
    'id':         id,
    'trip_id':    tripId,
    'user_id':    userId,
    'name':       name,
    'created_at': createdAt.toIso8601String(),
    'updated_at': updatedAt.toIso8601String(),
  };

  static PackingListModel fromEntity(PackingList l) => PackingListModel(
    id: l.id, tripId: l.tripId, userId: l.userId, name: l.name,
    items: l.items, createdAt: l.createdAt, updatedAt: l.updatedAt,
  );

  /// Override para que copyWith devuelva PackingListModel.
  @override
  PackingListModel copyWith({
    String? id, String? tripId, String? userId,
    String? name, List<PackingItem>? items,
    DateTime? createdAt, DateTime? updatedAt,
  }) => PackingListModel(
    id:        id        ?? this.id,
    tripId:    tripId    ?? this.tripId,
    userId:    userId    ?? this.userId,
    name:      name      ?? this.name,
    items:     items     ?? this.items,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
  );
}
