import 'package:flutter_test/flutter_test.dart';
import 'package:travel_ready/domain/entities/packing_item.dart';

import '../../helpers/fake_data.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  group('PackingItem', () {
    test('toggle: isPacked false → true', () {
      final item = PackingItem(
        id: '1', listId: 'l1', tripId: tTrip.id,
        name: 'Pasaporte', isPacked: false,
      );
      expect(item.toggle().isPacked, true);
    });

    test('toggle: isPacked true → false', () {
      final item = PackingItem(
        id: '1', listId: 'l1', tripId: tTrip.id,
        name: 'Pasaporte', isPacked: true,
      );
      expect(item.toggle().isPacked, false);
    });

    test('toggle no muta el original', () {
      final original = PackingItem(
        id: '1', listId: 'l1', tripId: tTrip.id,
        name: 'Pasaporte', isPacked: false,
      );
      original.toggle();
      expect(original.isPacked, false); // sin cambio
    });

    test('copyWith preserva campos no modificados', () {
      const item = PackingItem(
        id: '2', listId: 'l1', tripId: 'trip1',
        name: 'Cargador', category: PackingCategory.electronics,
        quantity: 2,
      );
      final copied = item.copyWith(name: 'Auriculares');
      expect(copied.name,     'Auriculares');
      expect(copied.category, PackingCategory.electronics);
      expect(copied.quantity, 2);
    });

    test('equatable — todos los campos iguales son iguales', () {
      const i1 = PackingItem(
          id: 'i1', listId: 'l1', tripId: 't1', name: 'A',
          isPacked: true, quantity: 2);
      const i2 = PackingItem(
          id: 'i1', listId: 'l1', tripId: 't1', name: 'A',
          isPacked: true, quantity: 2);
      expect(i1, equals(i2));
    });

    test('equatable — name diferente no son iguales', () {
      const i1 = PackingItem(
          id: 'i1', listId: 'l1', tripId: 't1', name: 'A');
      const i2 = PackingItem(
          id: 'i1', listId: 'l1', tripId: 't1', name: 'B');
      expect(i1, isNot(equals(i2)));
    });

    test('equatable — isPacked diferente no son iguales', () {
      const i1 = PackingItem(
          id: 'i1', listId: 'l1', tripId: 't1', name: 'A', isPacked: false);
      const i2 = PackingItem(
          id: 'i1', listId: 'l1', tripId: 't1', name: 'A', isPacked: true);
      expect(i1, isNot(equals(i2)));
    });

    test('quantity por defecto es 1', () {
      const item = PackingItem(
          id: 'x', listId: 'l', tripId: 't', name: 'Item');
      expect(item.quantity, 1);
    });

    test('isAutoGenerated por defecto es false', () {
      const item = PackingItem(
          id: 'x', listId: 'l', tripId: 't', name: 'Item');
      expect(item.isAutoGenerated, false);
    });
  });

  group('PackingList', () {
    test('progress = 0 si lista vacía', () {
      final list = PackingList(
        id: 'l1', tripId: 't1', name: 'Test',
        createdAt: DateTime(2026),
      );
      expect(list.progress, 0);
    });

    test('progress = 50 cuando la mitad está empaquetada', () {
      final list = PackingList(
        id: 'l1', tripId: tTrip.id, name: 'Test',
        createdAt: DateTime(2026),
        items: [
          PackingItem(id: '1', listId: 'l1', tripId: tTrip.id,
              name: 'A', isPacked: true),
          PackingItem(id: '2', listId: 'l1', tripId: tTrip.id,
              name: 'B', isPacked: false),
        ],
      );
      expect(list.progress,    50);
      expect(list.packedItems, 1);
      expect(list.totalItems,  2);
    });

    test('progress = 100 cuando todo está empaquetado', () {
      final list = tPackingList.copyWith(
        items: tPackingList.items.map((i) => i.copyWith(isPacked: true)).toList(),
      );
      expect(list.progress, 100);
    });

    test('packedItems cuenta correctamente items de fake_data', () {
      // tPackingList: 1 packed (item_02), 1 not packed (item_01)
      expect(tPackingList.packedItems, 1);
    });

    test('PackingCategoryLabel.label no está vacío', () {
      for (final cat in PackingCategory.values) {
        expect(cat.label.isNotEmpty, true,
            reason: 'label de $cat está vacío');
      }
    });

    test('PackingCategoryLabel.emoji no está vacío', () {
      for (final cat in PackingCategory.values) {
        expect(cat.emoji.isNotEmpty, true,
            reason: 'emoji de $cat está vacío');
      }
    });
  });
}
